author = "Sanya Shetty"
baseURL = 'https://sanyashetty.github.io/hugo-mock-landing-page-autodeployed/'
copyright = "Sanya Shetty"
title = "NutriScale"

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"

disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
author = "authors"
category = "categories"
series = 'series'
tag = "tags"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
[module.hugoVersion]
extended = true
max = ""
min = "0.99.1"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "static"
target = "static"
